"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000
add_newline = false

format = """
$os$directory \
${custom.giturl} \
$git_branch \
$git_status\
$git_metrics\
$line_break\
$character
"""

right_format = """
$cmd_duration\
$time
"""

[os]
disabled = false
format = "[$output]($style)"

[os.symbols]
Windows = "ó°² "
Ubuntu = "ó°•ˆ "
SUSE = "ïŒ” "
Raspbian = "ó°¿ "
Mint = "ó°£­ "
Macos = " îœ‘ "
Manjaro = "ïŒ’ "
Linux = "ó°Œ½ "
Gentoo = "ó°£¨ "
Fedora = "ó°£› "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "îœ "
Arch = "ó°£‡ "
Artix = "ó°£‡ "
CentOS = "ïŒ„ "
Debian = "ó°£š "
Redhat = "ó±„› "
RedHatEnterprise = "ó±„› "

# [username]
#show_always = true
#style_user = "bg:surface0 fg:text"
#style_root = "bg:surface0 fg:text"
#format = '[ $user ]($style)'

[directory]
style = "bold blue"
format = "[$path]($style)"
truncate_to_repo = false
truncation_length = 7

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "
"~" = "ï€• "

[custom.giturl]
# disabled = true
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL="ïˆ "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL="ïŠ– "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL="ï…± "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL="ï¡ "
else
    GIT_REMOTE_SYMBOL="ï‡’ "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "at $output "

[git_branch]
symbol = "ï˜ "
style = "green"
format =  'on [$symbol$branch(:$remote_branch)]($style)'

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
format = '$ahead_behind([\[($all_status)\]]($style) )'

[git_metrics]
disabled = false
added_style = 'bold green'
deleted_style = 'bold red'
format = '[+$added]($added_style)/[-$deleted]($deleted_style)'

[character]
disabled = false
success_symbol = '[â¯](bold green)'
error_symbol = '[ğ˜¹](bold red)'
vimcmd_symbol = '[îŸ…](green)'
vimcmd_replace_one_symbol = '[îŸ…](bold purple)'
vimcmd_replace_symbol = '[îŸ…](bold purple)'
vimcmd_visual_symbol = '[îŸ…](bold lavender)'

[nodejs]
symbol = "îœ˜ "
format = '[$symbol$version]($style)'

[c]
symbol = "î˜ "
format = '[$symbol$version]($style)'

[cpp]
symbol = "î£ "
format = '[$symbol$version]($style)'

[rust]
symbol = "î¨ "
format = '[$symbol$version]($style)'

[golang]
symbol = "î˜§ "
format = '[$symbol$version]($style)'
detect_files = ["go.mod"]

[php]
symbol = "î˜ˆ "
format = '[$symbol$version]($style)'

[java]
symbol = "î‰– "
format = '[$symbol$version]($style)'

[kotlin]
symbol = "î˜´ "
format = '[$symbol$version]($style)'

[haskell]
symbol = "î˜Ÿ "
format = '[$symbol$version]($style)'

[python]
symbol = "î˜† "
format = '[$symbol$version]($style)'

[docker_context]
symbol = "ïŒˆ "
format = '[$symbol$context]($style)'

[time]
disabled = false
time_format = "%T"
style = '#404040'
format = '[ïº $time]($style)'

# [transient_character]
# success_symbol = '[â¯](bold green)'
# error_symbol = '[â¯](bold red)'
